[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
healthcheckGracePeriod = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
